# yaml 配置
version: "3.7"
services:
  mysql:
    image: "mysql:5.7.40"
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "go_cron"
      LANG: "C.UTF-8"
    volumes:
      - ./init-db/:/docker-entrypoint-initdb.d/
  server:
    build: ./server
    container_name: server
    depends_on:
      - mysql
    command: sh -c "./wait-for-it.sh mysql:3306 -- ./cron-server ./configs/config.yaml"
    ports:
      - "8888:8888"
