# yaml 配置
version: "3.7"
services:
  mysql:
    image: "mysql:5.7.40"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "go_cron"
      LANG: "C.UTF-8"
    volumes:
      - ./init-db/:/docker-entrypoint-initdb.d/
    ports:
      - "33061:3306"
  server:
    build: ./
    container_name: server
    depends_on:
      - mysql
    command: sh -c "./wait-for-it.sh mysql:3306 -- ./server ./configs/config.yaml"
    ports:
      - "8888:8888"
  front:
    build: ./assets
    container_name: front
    depends_on:
      - mysql
      - server
    ports:
      - "8800:80"

